function thres = CheckThres_2

G_names = who('global');

Index_var1 = strfind(G_names, 'exp_');
Index_var = find(not(cellfun('isempty', Index_var1)));

Index_low1 = strfind(G_names, 'low_');
Index_low = find(not(cellfun('isempty', Index_low1)));

Index_hig1 = strfind(G_names, 'hig_');
Index_hig = find(not(cellfun('isempty', Index_hig1)));

extistData = isempty(Index_var);
if extistData == 0

NEle = numel(Index_var);
eval (['global ' G_names{Index_var(1)}]);
eval (['global ' G_names{Index_hig(1)}]);
eval (['global ' G_names{Index_low(1)}]);
eval (['refmat =' G_names{Index_var(1)} '.refmat']);
eval (['size =' G_names{Index_var(1)} '.size']);

for i = 1:NEle
    eval (['global ' G_names{Index_var(i)}]);
    eval ([G_names{Index_var(i)} '.refmat =' G_names{Index_var(1)} '.refmat']);
    eval ([G_names{Index_var(i)} '.size =' G_names{Index_var(1)} '.size']);
    eval (['global ' G_names{Index_hig(i)}]);
    eval (['global ' G_names{Index_low(i)}]);
end

if NEle <= 1;
    eval (['thres=and(' G_names{Index_var(1)} '>' G_names{Index_low(1)} ','...
        G_names{Index_var(1)} '<' G_names{Index_hig(1)} ')' ]);
else
    choice = questdlg('Join thresholds using...', ...
        'Join thresholds','AND','OR','AND');
    switch choice
        case 'AND'
            dessert = 1;
        case 'OR'
            dessert = 2;
    end

    if dessert == 1
        if NEle ==2
            eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
                '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
                '&' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
                '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}]);
        
    elseif NEle ==3
        eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
            '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
            '&' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
            '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}...
            '&' G_names{Index_var(3)} '>' G_names{Index_low(3)}...
            '&' G_names{Index_var(3)} '<' G_names{Index_hig(3)}]);   

    elseif NEle ==4
        eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
            '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
            '&' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
            '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}...
            '&' G_names{Index_var(3)} '>' G_names{Index_low(3)}...
            '&' G_names{Index_var(3)} '<' G_names{Index_hig(3)}...
            '&' G_names{Index_var(4)} '>' G_names{Index_low(4)}...
            '&' G_names{Index_var(4)} '<' G_names{Index_hig(4)}]); 

    elseif NEle ==5
        eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
            '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
            '&' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
            '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}...
            '&' G_names{Index_var(3)} '>' G_names{Index_low(3)}...
            '&' G_names{Index_var(3)} '<' G_names{Index_hig(3)}...
            '&' G_names{Index_var(4)} '>' G_names{Index_low(4)}...
            '&' G_names{Index_var(4)} '<' G_names{Index_hig(4)}...
            '&' G_names{Index_var(5)} '>' G_names{Index_low(5)}...
            '&' G_names{Index_var(5)} '<' G_names{Index_hig(5)}]);

    elseif NEle > 5
        eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
            '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
            '&' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
            '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}...
            '&' G_names{Index_var(3)} '>' G_names{Index_low(3)}...
            '&' G_names{Index_var(3)} '<' G_names{Index_hig(3)}...
            '&' G_names{Index_var(4)} '>' G_names{Index_low(4)}...
            '&' G_names{Index_var(4)} '<' G_names{Index_hig(4)}...
            '&' G_names{Index_var(5)} '>' G_names{Index_low(5)}...
            '&' G_names{Index_var(5)} '<' G_names{Index_hig(5)}...
            '&' G_names{Index_var(6)} '>' G_names{Index_low(6)}...
            '&' G_names{Index_var(6)} '<' G_names{Index_hig(6)}]);
        end

    elseif dessert == 2
        if NEle ==2
            eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
                '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
                '|' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
                '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}]);
        
        elseif NEle ==3
            eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
                '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
                '|' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
                '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}...
                '|' G_names{Index_var(3)} '>' G_names{Index_low(3)}...
                '&' G_names{Index_var(3)} '<' G_names{Index_hig(3)}]);   
            
        elseif NEle ==4
            eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
                '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
                '|' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
                '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}...
                '|' G_names{Index_var(3)} '>' G_names{Index_low(3)}...
                '&' G_names{Index_var(3)} '<' G_names{Index_hig(3)}...
                '|' G_names{Index_var(4)} '>' G_names{Index_low(4)}...
                '&' G_names{Index_var(4)} '<' G_names{Index_hig(4)}]); 

        elseif NEle ==5
            eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
                '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
                '|' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
                '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}...
                '|' G_names{Index_var(3)} '>' G_names{Index_low(3)}...
                '&' G_names{Index_var(3)} '<' G_names{Index_hig(3)}...
                '|' G_names{Index_var(4)} '>' G_names{Index_low(4)}...
                '&' G_names{Index_var(4)} '<' G_names{Index_hig(4)}...
                '|' G_names{Index_var(5)} '>' G_names{Index_low(5)}...
                '&' G_names{Index_var(5)} '<' G_names{Index_hig(5)}]);
            
        elseif NEle > 5
            eval (['thres=' G_names{Index_var(1)} '>' G_names{Index_low(1)}...
                '&' G_names{Index_var(1)} '<' G_names{Index_hig(1)}...
                '|' G_names{Index_var(2)} '>' G_names{Index_low(2)}...
                '&' G_names{Index_var(2)} '<' G_names{Index_hig(2)}...
                '|' G_names{Index_var(3)} '>' G_names{Index_low(3)}...
                '&' G_names{Index_var(3)} '<' G_names{Index_hig(3)}...
                '|' G_names{Index_var(4)} '>' G_names{Index_low(4)}...
                '&' G_names{Index_var(4)} '<' G_names{Index_hig(4)}...
                '|' G_names{Index_var(5)} '>' G_names{Index_low(5)}...
                '&' G_names{Index_var(5)} '<' G_names{Index_hig(5)}...
                '|' G_names{Index_var(6)} '>' G_names{Index_low(6)}...
                '&' G_names{Index_var(6)} '<' G_names{Index_hig(6)}]);
        end        
    end
end

else
   errordlg('calculate threshold in geobia ','File Error'); 
end

end



